//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFSJ.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UFSJ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlackTheme {
            get {
                object obj = ResourceManager.GetObject("BlackTheme", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;item Key=&apos;#B.1#&apos;&gt;Split&lt;/item&gt;
        ///    &lt;item Key=&apos;#B.2#&apos;&gt;Join&lt;/item&gt;
        ///    &lt;item Key=&apos;#B.3#&apos;&gt;Calculate&lt;/item&gt;
        ///    &lt;item Key=&apos;#B.4#&apos;&gt;Compare&lt;/item&gt;
        ///    &lt;item Key=&apos;#B.5#&apos;&gt;Manage&lt;/item&gt;
        ///    &lt;item Key=&apos;#B.6#&apos;&gt;Open Output Directory&lt;/item&gt;
        ///    &lt;item Key=&apos;#B.7#&apos;&gt;Open Output File&lt;/item&gt;
        ///    &lt;item Key=&apos;#B.8#&apos;&gt;View Summary&lt;/item&gt;
        ///    &lt;item Key=&apos;#B.9#&apos;&gt;OK&lt;/item&gt;
        ///    &lt;item Key=&apos;#B.A#&apos;&gt;Apply&lt;/item&gt;
        ///    &lt;item Key=&apos;#B.B#&apos;&gt;Browse&lt;/item&gt;
        ///    &lt;item Key=&apos;#B.C#&apos;&gt;Yes&lt;/item&gt;
        ///    &lt;item Key=&apos;#B.D#&apos;&gt;No&lt;/item&gt;
        ///    &lt;item Key=&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultStrings {
            get {
                return ResourceManager.GetString("DefaultStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Template {
            get {
                object obj = ResourceManager.GetObject("Template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UFSJT {
            get {
                object obj = ResourceManager.GetObject("UFSJT", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
